version: '3.8'
services:
  nest:
    container_name: clapsit-main-server-nest_dev
    ports:
      - "3333:3333"
    depends_on:
      - mysql
    volumes:
      - .:/clapsit/clapsit-main-server-refactor
      - /clapsit/clapsit-main-server-refactor/node_modules
    command: sh -c "pnpm run db:generate && pnpm run db:deploy && pnpm run start:dev"
