version: '3.8'
services:
  nest:
    container_name: clapsit-main-server-nest_build
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mysql
    command: sh -c "pnpm run db:generate && pnpm run db:deploy && pnpm run start:prod"
